'Problem: Bug':
    - head-branch: ['^hotfix']
    - head-branch: ['^fix']
    - head-branch: ['^bug']
'Type: New Feature':
    - head-branch: ['^feat']
'Type: Improvement':
    - head-branch: ['^refactor']
'Type: Chore':
    - head-branch: ['^renovate/']
