name: Assign

on:
    pull_request:
        types: [opened, synchronize]
    issues:
        types: [opened]

jobs:
    assign-label:
        needs: sync-labels
        if: ${{ github.event_name == 'pull_request' }}
        permissions:
            contents: read
            pull-requests: write
            issues: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: Apply labels from branch
              uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labels/labeling-branch.yaml
            - name: Apply labels from changed files
              uses: actions/labeler@bf12e9b00b37c5c0ca2b87b79b2daf7891dbda13 # v7
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labels/labeling-files.yaml

    sync-labels:
        permissions:
            issues: write
            contents: read
            pages: write
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: '24.21.0'
            - uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
            - name: Run github-label-setup
              run: pnpm dlx --yes @azu/github-label-setup --token ${{ secrets.GITHUB_TOKEN }} --labels .github/labels/labels.json

    assign-author:
        if: ${{ ! contains(fromJson('["renovate[bot]", "dependabot[bot]"]'), github.actor) }}
        permissions:
            issues: write
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: technote-space/assign-author@9558557c5c4816f38bd06176fbc324ba14bb3160 # v1
